### ISSUE TITLE
Thoughts about having the ability to set corner radius?

### ISSUE THREAD

**Issue by InYourDreamz** [xgc1986/RippleButton#2]
So far your library is exactly what I needed! Do you have plans to allow users to set the corner radius?

**Comment by xgc1986** [comment]
that's independent of the ripple Effect, if the view has already a corner radius the ripple effect should have the expected behaviour.

But if you show me the piece of code, maybe I will understand better what you need or how to fix it

**Comment by xgc1986** [comment]
This library only adds the ripple effect, but if you found a library allows you to change the corner radius, this library has RippleDrawableHelper that adds the ripple effect to whatever view. I don't force you to use RippleButton class, this class was just created to save some time to the developers because it is the most common class to have this effect

**Comment by xgc1986** [comment]
This library only adds the ripple effect, but if you found a library allows you to change the corner radius, this library has RippleDrawableHelper that adds the ripple effect to whatever view. I don't force you to use RippleButton class, this class was just created to save some time to the developers because it is the most common class to have this effect
